
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/multi_thread?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 429006huzhuo

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml